// src/app/layout.tsx
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from './context/ThemeContext';
// Убедитесь, что путь правильный

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Bookify',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}></body>
    </html>
  );
}
